filetype off
set rtp+=../../../plugged/vader.vim/
set rtp+=../../../plugged/vim-fugitive/
set rtp+=../../vader.vim/
set rtp+=../../vim-fugitive/
set rtp+=../vader.vim/
set rtp+=../vim-fugitive/
set rtp+=../
filetype plugin indent on
syntax enable
set nomore
set noswapfile
set viminfo=
