filetype off
set runtimepath+=../../../plugged/vader.vim/
set runtimepath+=../../../plugged/vim-fugitive/
set runtimepath+=../../vader.vim/
set runtimepath+=../../vim-fugitive/
set runtimepath+=../vader.vim/
set runtimepath+=../vim-fugitive/
set runtimepath+=../
filetype plugin indent on
syntax enable
set nomore
set noswapfile
set viminfo=
